#!/usr/bin/env python3
"""Fetch products from dummyjson.com and emit a seed SQL file with matching images.

Output: seed-dummyjson.sql  (run it on Neon to replace the demo catalog).
"""
import json
import urllib.request

URL = "https://dummyjson.com/products?limit=0&select=title,description,price,discountPercentage,stock,category,thumbnail,images"
OUT = "seed-dummyjson.sql"

# Map dummyjson categories -> the store's 6 Spanish categories.
CATEGORY_MAP = {
    "smartphones": "Electrónica", "laptops": "Electrónica", "tablets": "Electrónica",
    "mobile-accessories": "Electrónica", "mens-watches": "Electrónica", "womens-watches": "Electrónica",
    "furniture": "Hogar", "home-decoration": "Hogar", "kitchen-accessories": "Hogar", "groceries": "Hogar",
    "mens-shirts": "Ropa", "mens-shoes": "Ropa", "tops": "Ropa", "womens-dresses": "Ropa",
    "womens-shoes": "Ropa", "womens-bags": "Ropa", "womens-jewellery": "Ropa", "sunglasses": "Ropa",
    "beauty": "Ropa", "fragrances": "Ropa", "skin-care": "Ropa",
    "sports-accessories": "Deportes", "motorcycle": "Deportes", "vehicle": "Deportes",
}

SELLER = "(SELECT id FROM users WHERE role IN ('Seller','Admin') ORDER BY id LIMIT 1)"


def esc(s):
    return (s or "").replace("'", "''")


def main():
    req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0 (seed-generator)"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.load(resp)
    products = data["products"]

    rows = []
    for p in products:
        name = esc(p["title"])[:255]
        desc = esc(p.get("description", ""))
        stock = int(p.get("stock", 0))
        price = round(float(p["price"]), 2)
        disc = float(p.get("discountPercentage", 0) or 0)
        sale = "NULL"
        if disc >= 8:
            sale = str(round(price * (1 - disc / 100), 2))
        imageurl = esc(p.get("thumbnail", ""))
        imgs = [esc(u) for u in (p.get("images") or [])][:4]
        if imgs:
            images = "ARRAY[" + ",".join("'" + u + "'" for u in imgs) + "]::text[]"
        else:
            images = "ARRAY[]::text[]"
        category = CATEGORY_MAP.get(p.get("category", ""), "Otros")

        rows.append(
            f"('{name}', '{desc}', {stock}, {price}, {sale}, "
            f"'{imageurl}', {images}, '{category}', {SELLER})"
        )

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("-- Replace the demo catalog with real products imported from dummyjson.com.\n")
        f.write("-- Wipes products + orders/reviews/variants, then inserts fresh data with matching images.\n")
        f.write("-- Generated by generate-dummyjson-seed.py — do not edit by hand.\n\n")
        f.write("BEGIN;\n\n")
        f.write("TRUNCATE TABLE product, orders RESTART IDENTITY CASCADE;\n\n")
        f.write("INSERT INTO product (name, description, stock, price, sale_price, imageurl, images, category, seller_id) VALUES\n")
        f.write(",\n".join(rows))
        f.write(";\n\nCOMMIT;\n")

    print(f"Wrote {OUT} with {len(rows)} products")


if __name__ == "__main__":
    main()
